services:
  # Redis Cache (если не установлен локально)
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # F1 News Bot (Main App + Telegram Bot)
  f1-news-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://f1_user:f1_password@host.docker.internal:5432/f1_news
      - REDIS_URL=redis://redis:6379/0
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=llama3:latest
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data:
