services:
  # Telegram Bot (отдельный контейнер)
  f1-news-bot-telegram:
    build: .
    environment:
      - DATABASE_URL=postgresql://f1_user:f1_password@host.docker.internal:5432/f1_news
      - REDIS_URL=redis://host.docker.internal:6379/0
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_ID=${TELEGRAM_CHANNEL_ID}
      - TELEGRAM_ADMIN_ID=${TELEGRAM_ADMIN_ID}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["python", "telegram_bot_standalone.py"]
